[package]
name = "Liquidswap"
version = "0.4.4"
upgrade_policy = "immutable"

[addresses]
liquidswap = "0x43417434fd869edee76cca2a4d2301e528a1551b1d719b75c350c3c97d15b8b9"

# Admins
dao_admin = "0x54c6f803a21b973ccb2b24b81309f12298fe6b66fe0b4efafa5ccf2973691196"
emergency_admin = "0x54c6f803a21b973ccb2b24b81309f12298fe6b66fe0b4efafa5ccf2973691196"
fee_admin = "0x54c6f803a21b973ccb2b24b81309f12298fe6b66fe0b4efafa5ccf2973691196"

# Resource accounts: should be the same as @liquidswap_lp in lp_coin
liquidswap_pool_account = "0xf5f11a0fa0ef6e2cd215d73cc3bd3c4cc2ad5b1c24625a690aadc9b13a57eaff"
liquidswap_emergency_account = "0x310ea81ab7bc896df3d1dd2f84392a1a4796d66ac4237ee6d760f88df837706f"

# Addresses for tests.
test_coin_admin = "0x11"
test_helpers = "0x12"

test_lp_owner = "0x12"
test_pool_addr = "0x2540b6f8a87ac1cff2de9f5f742854b448cd4521e96f840eda05e63e4e944ed6"

[dependencies.LiquidswapLP]
local = "./liquidswap_lp/"

[dependencies.LiquidswapInit]
local = "./liquidswap_init/"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "main"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.UQ64x64]
git = "https://github.com/pontem-network/UQ64x64.git"
rev = "v0.3.8"

[dependencies.U256]
git = "https://github.com/pontem-network/U256.git"
rev = "v0.3.9"
