[package]
name = "Liquidswap"
version = "0.4.0"
upgrade_policy = "immutable"

[addresses]
liquidswap = "0x4e9fce03284c0ce0b86c88dd5a46f050cad2f4f33c4cdd29d98f501868558c81"

# Admins
dao_admin = "0x4dd8990e4133ac30abee14bca0736988a8ec37bdef33952e99aa055289826501"
emergency_admin = "0x4dd8990e4133ac30abee14bca0736988a8ec37bdef33952e99aa055289826501"
fee_admin = "0x4dd8990e4133ac30abee14bca0736988a8ec37bdef33952e99aa055289826501"

# Resource accounts: should be the same as @liquidswap_lp in lp_coin
liquidswap_pool_account = "0x8aa500cd155a6087509fa84bc7f0deed3363dd253ecb62b2f110885dacf01c67"
liquidswap_emergency_account = "0x65f12ace6df9511f3b5b59c17ea5961808034965a439a9d2cdc3f810616f5156"

# Addresses for tests.
test_coin_admin = "0x11"
test_helpers = "0x12"

test_lp_owner = "0x12"
test_pool_addr = "0x2540b6f8a87ac1cff2de9f5f742854b448cd4521e96f840eda05e63e4e944ed6"

[dependencies.LiquidswapLP]
local = "./liquidswap_lp"

[dependencies.LiquidswapInit]
local = "./liquidswap_init"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "985f19d40457a5f09f2d741b1feca6bf7ba1f8a6"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.UQ64x64]
git = "https://github.com/pontem-network/UQ64x64.git"
rev = "v0.3.7"

[dependencies.U256]
git = "https://github.com/pontem-network/U256.git"
rev = "v0.3.8"

[dev-dependencies.TestCoins]
git = "https://github.com/pontem-network/test-coins.git"
rev = "v0.1.2"
