[package]
name = "Liquidswap"
version = "0.2.0"

[addresses]
liquidswap = "0x43417434fd869edee76cca2a4d2301e528a1551b1d719b75c350c3c97d15b8b9"
dao_admin = "0xb4d7b2466d211c1f4629e8340bb1a9e75e7f8fb38cc145c54c5c9f9d5017a318"

# Addresses for tests.
test_coin_admin = "0x11"
test_pool_owner = "0x12"

[dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "a3143756d498821f4f51a5970c7ea35d483938b3"
subdir = "aptos-move/framework/move-stdlib"

[dependencies.MoveNursery]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "a3143756d498821f4f51a5970c7ea35d483938b3"
subdir = "aptos-move/framework/move-stdlib/nursery"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "a3143756d498821f4f51a5970c7ea35d483938b3"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.UQ64x64]
git = "https://github.com/pontem-network/UQ64x64.git"
rev = "v0.3.0"

[dependencies.U256]
git = "https://github.com/pontem-network/U256.git"
rev = "v0.3.0"